name: "CI - Nix"

on:
  push:
    branches:
    - humble_devel
  pull_request:
    branches:
    - humble_devel

jobs:
  nix:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gepetto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: ros
      - run: nix build -L .#agimus-controller-examples .#agimus-controller-ros
